
// Generated by import script...
#include <WiFi.h>
#define ARDUINO 1

void setup();
void loop();
void do_keyboard();
void do_keyboard_terminal();
void do_mouse();
void boot_screen();
void debug_log(const char *format, ...);
void switchTerminalMode();
void print(char const * text);
void printFmt(const char *format, ...);
